shim-version: v0.4.2@sha256:d65f769e37bbe86ffaeef42120c29c4b9de33415fcd7588a9ef7a64f609aa2a3
cvm-version: 0.6.9
cpus: 8
memory: 65536

containers:
  - name: "inference-verifier"
    image: "ghcr.io/setting-three-security/inference-verification-tee:v0.9.12@sha256:5060f38cb2c6ef76e40596531dba5c65648d70ee81b7c06207f5e37f311f70f0"
    runtime: nvidia
    gpus: all
    secrets:
      - HF_TOKEN
      - OPENROUTER_DEMO

shim:
  listen-port: 443
  upstream-port: 8080
  paths:
    - /verify
    - /verify-stream
    - /query
    - /verify-text
    - /verify-text-stream
    - /health
    - /config
    - /ui
