cvm-version: 0.7.3
memory: 65536
cpus: 8
gpus: 1

containers:
  - name: "inference-verifier"
    image: "ghcr.io/setting-three-security/inference-verification-tee:v0.9.20@sha256:f69e33e1978d67733d68ae39054b6054a247487b75a3b59d9a12479a722dec07"
    runtime: nvidia
    gpus: all
    secrets:
      - HF_TOKEN
      - OPENROUTER_DEMO

shim:
  upstream-port: 8080
  paths:
    - /verify
    - /verify-stream
    - /query
    - /verify-text
    - /verify-text-stream
    - /health
    - /config
    - /ui
